export const SECTORS = [
  'Informatique',
  'Finance',
  'Santé',
  'Éducation',
  'Industrie',
  'Commerce',
  'Marketing',
  'Juridique',
  'Transport',
  'Énergie',
  'Média',
  'Agroalimentaire',
  'Consulting',
  'Immobilier',
  'Tourisme / Hôtellerie',
  'Sport',
  'Culture',
  'Public / Administration',
  'Association / ONG',
  'Recherche',
  'Assurance',
  'Arts / Design',
  'Environnement',
  'Logistique',
  'Automobile',
  'Aéronautique / Spatial',
  'Télécom',
  'Construction',
  'Audiovisuel / Cinéma',
  'Freelance / Entrepreneur',
  'Autre',
];
