-- 004: Add tag column to QUESTION for KPI identification

ALTER TABLE QUESTION ADD COLUMN IF NOT EXISTS tag VARCHAR(100) DEFAULT NULL;
CREATE INDEX IF NOT EXISTS idx_question_tag ON QUESTION(tag) WHERE tag IS NOT NULL;
